os:
  - osx
language: C++
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev

before_install:
 - brew update
 - brew outdated python || brew upgrade python

script: pwd && ruby ./Hello.rb
