os:
  - OSX
  
language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo wget http://download.opensuse.org/repositories/home:fbergman:libsbml/xUbuntu_14.04/Release.key
    - sudo apt-key add - < Release.key  
    - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/fbergman:/libsbml/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/python-libsbml.list"
    - sudo apt-key update
    - sudo apt-get update -qq
    - sudo apt-get install -y libxml2-dev
    - sudo apt-get install -y libz-dev
    - sudo apt-get install -y libbz2-dev
script:    
    - brew brew tap homebrew/science
    - brew install libsbml
    
     pwd && ruby ./Hello.rb
