language: objective-c
  
before_install:
    - sudo apt-get install -y libxml2-dev
    - sudo apt-get install -y libz-dev
    - sudo apt-get install -y libbz2-dev
    - brew update
    - brew brew tap homebrew/science
    - brew install libsbml

    
script:    
     pwd && ruby ./Hello.rb
