os:
  - osx
language: php
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
script: phpunit Test.php  &&  pwd  && ruby ./Hello.rb
