os:
  - osx
language: php
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - python-dev
    - python-numpy
    - libxml2-dev
    - zlib1g-dev
    - libbz2-dev
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php  &&  pwd  && ruby ./Hello.rb
